version: '3'

services:
  hack19_db:
    image: postgres
    container_name: Hack19-Postgres-Development
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres-hack19:/var/lib/postgresql/data
  hack19_web:
    container_name: Hack19-Django-Development
    build:
      context: ../../
      dockerfile: Deployment/Development/Dockerfile
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      PGPASSWORD: ${PGPASSWORD}
      DEBUG: ${DEBUG}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_STORAGE_BUCKET_NAME: ${S3_STORAGE_BUCKET_NAME}
      STATIC_URL: ${STATIC_URL}
      AWS_DEFAULT_ACL: ${AWS_DEFAULT_ACL}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      CDN: ${CDN}
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"
    depends_on:
      - hack19_db
volumes:
  postgres-hack19:
    driver: local